
x80sv:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10

  left_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_as
    pid: {p: 5.0, i: 1.0, d: 5.0}

  right_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_as
    pid: {p: 5.0, i: 1.0, d: 5.0}
